#!/bin/bash -e
mix edeliver build release --verbose
mix edeliver stop production --verbose
mix edeliver deploy release to production --verbose
mix edeliver start production --verbose
mix edeliver migrate production up --verbose
